# Generated by Django 3.1.4 on 2020-12-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('dentist', 'стоматолог'), ('surgeon', 'хирург'), ('therapist', 'терапевт')], max_length=255, verbose_name='специальность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
                'ordering': ['specialty', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor', models.CharField(max_length=255, verbose_name='пациент')),
                ('date', models.DateField(verbose_name='дата приёма')),
                ('time', models.IntegerField(choices=[(9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00')], verbose_name='время приёма')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.doctor', verbose_name='врач')),
            ],
            options={
                'verbose_name': 'приём у врача',
                'verbose_name_plural': 'приёмы у врачей',
                'ordering': ['date', 'time', 'doctor'],
                'unique_together': {('date', 'time', 'doctor')},
            },
        ),
    ]
